# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    build: ./mysql
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # node 이미지를 지정
  node:
    build: ./node
    restart: always
    links:
      - db:db_url
    ports:
      - 3000:3000
